project:
  type: website

website:
  title: "PGWP"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: demands.qmd
        text: Demands
      - href: events.qmd
        text: Events
      - href: donations.qmd
        text: Donations
      - href: contact.qmd
        text: Contact
      
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



